-- MySQL 方言覆盖：网站、域名、配置版本三表。
CREATE TABLE `web_site` (
  `id` BIGINT NOT NULL,
  `node_id` BIGINT NOT NULL DEFAULT 0 COMMENT '所在节点ID，0 为主控',
  `name` VARCHAR(128) NOT NULL COMMENT '站点标识，同时作为配置文件名',
  `type` VARCHAR(32) NOT NULL DEFAULT 'static' COMMENT 'static/php/proxy/java/node/python/go',
  `server_type` VARCHAR(32) NOT NULL DEFAULT 'nginx' COMMENT 'nginx/openresty',
  `root_path` VARCHAR(512) NOT NULL DEFAULT '',
  `index_files` VARCHAR(255) NOT NULL DEFAULT 'index.html index.htm',
  `runtime_id` BIGINT NOT NULL DEFAULT 0,
  `php_version` VARCHAR(32) NOT NULL DEFAULT '',
  `proxy_target` VARCHAR(512) NOT NULL DEFAULT '' COMMENT '反代目标 URL',
  `proxy_host` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '回源 Host 头',
  `proxy_websocket` TINYINT(1) NOT NULL DEFAULT 1,
  `listen_port` INT NOT NULL DEFAULT 80,
  `ssl_port` INT NOT NULL DEFAULT 443,
  `ssl_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `cert_id` BIGINT NOT NULL DEFAULT 0,
  `force_https` TINYINT(1) NOT NULL DEFAULT 0,
  `http2_enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `http3_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `waf_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `access_log_enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `error_log_enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `access_log_path` VARCHAR(512) NOT NULL DEFAULT '',
  `error_log_path` VARCHAR(512) NOT NULL DEFAULT '',
  `rate_limit_json` TEXT,
  `status` VARCHAR(32) NOT NULL DEFAULT 'running' COMMENT 'running/stopped/error/deploying/maintenance',
  `config_version` INT NOT NULL DEFAULT 1,
  `expire_at` DATETIME(3) NULL,
  `group_name` VARCHAR(64) NOT NULL DEFAULT 'default',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  `deleted_at` DATETIME(3) NULL,
  `created_by` BIGINT NOT NULL DEFAULT 0,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_site_node_name` (`node_id`,`name`,`deleted_at`),
  KEY `idx_site_status` (`status`,`deleted_at`),
  KEY `idx_site_cert` (`cert_id`),
  KEY `idx_site_tenant` (`tenant_id`,`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='网站表';

CREATE TABLE `web_site_domain` (
  `id` BIGINT NOT NULL,
  `site_id` BIGINT NOT NULL,
  `domain` VARCHAR(255) NOT NULL COMMENT '域名，支持 *.example.com',
  `port` INT NOT NULL DEFAULT 80,
  `is_primary` TINYINT(1) NOT NULL DEFAULT 0,
  `is_wildcard` TINYINT(1) NOT NULL DEFAULT 0,
  `cert_id` BIGINT NOT NULL DEFAULT 0,
  `dns_resolved_ip` VARCHAR(64) NOT NULL DEFAULT '',
  `dns_check_at` DATETIME(3) NULL,
  `dns_check_result` VARCHAR(32) NOT NULL DEFAULT '',
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  `deleted_at` DATETIME(3) NULL,
  `created_by` BIGINT NOT NULL DEFAULT 0,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_domain_port` (`domain`,`port`,`deleted_at`),
  KEY `idx_domain_site` (`site_id`,`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='网站域名表';

CREATE TABLE `web_site_config` (
  `id` BIGINT NOT NULL,
  `site_id` BIGINT NOT NULL,
  `version` INT NOT NULL COMMENT '站点内自增版本号',
  `config_type` VARCHAR(32) NOT NULL DEFAULT 'nginx',
  `content` TEXT NOT NULL,
  `content_hash` VARCHAR(64) NOT NULL,
  `source` VARCHAR(32) NOT NULL DEFAULT 'panel' COMMENT 'panel/manual_edit/import/rollback',
  `is_current` TINYINT(1) NOT NULL DEFAULT 0,
  `deploy_status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'pending/deployed/failed/rolled_back',
  `deploy_at` DATETIME(3) NULL,
  `deploy_error` VARCHAR(512) NOT NULL DEFAULT '',
  `change_summary` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  `deleted_at` DATETIME(3) NULL,
  `created_by` BIGINT NOT NULL DEFAULT 0,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cfg_site_version` (`site_id`,`config_type`,`version`),
  KEY `idx_cfg_current` (`site_id`,`is_current`),
  KEY `idx_cfg_hash` (`content_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='网站配置版本表';
