-- MySQL 方言覆盖：用户与会话。
CREATE TABLE `sys_user` (
  `id` BIGINT NOT NULL,
  `username` VARCHAR(64) NOT NULL,
  `nickname` VARCHAR(64) NOT NULL DEFAULT '',
  `email` VARCHAR(128) NOT NULL DEFAULT '',
  `mobile` VARCHAR(32) NOT NULL DEFAULT '',
  `password_hash` VARCHAR(128) NOT NULL,
  `avatar` VARCHAR(512) NOT NULL DEFAULT '',
  `status` VARCHAR(32) NOT NULL DEFAULT 'active',
  `is_super` TINYINT(1) NOT NULL DEFAULT 0,
  `two_factor_enabled` TINYINT(1) NOT NULL DEFAULT 0,
  `allow_ip_json` TEXT,
  `last_login_at` DATETIME(3) NULL,
  `last_login_ip` VARCHAR(64) NOT NULL DEFAULT '',
  `login_fail_count` INT NOT NULL DEFAULT 0,
  `locked_until` DATETIME(3) NULL,
  `password_updated_at` DATETIME(3) NULL,
  `must_change_password` TINYINT(1) NOT NULL DEFAULT 0,
  `lang` VARCHAR(16) NOT NULL DEFAULT 'zh-CN',
  `timezone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  `deleted_at` DATETIME(3) NULL,
  `created_by` BIGINT NOT NULL DEFAULT 0,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_username` (`tenant_id`,`username`,`deleted_at`),
  KEY `idx_user_email` (`email`),
  KEY `idx_user_status` (`status`,`deleted_at`),
  KEY `idx_user_tenant` (`tenant_id`,`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

CREATE TABLE `sys_session` (
  `id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `jti` VARCHAR(64) NOT NULL,
  `refresh_token_hash` VARCHAR(128) NOT NULL,
  `device_type` VARCHAR(32) NOT NULL DEFAULT 'web',
  `user_agent` VARCHAR(512) NOT NULL DEFAULT '',
  `client_ip` VARCHAR(64) NOT NULL DEFAULT '',
  `login_at` DATETIME(3) NOT NULL,
  `last_active_at` DATETIME(3) NOT NULL,
  `access_expire_at` DATETIME(3) NOT NULL,
  `refresh_expire_at` DATETIME(3) NOT NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'active',
  `revoke_reason` VARCHAR(128) NOT NULL DEFAULT '',
  `created_at` DATETIME(3) NOT NULL,
  `updated_at` DATETIME(3) NOT NULL,
  `created_by` BIGINT NOT NULL DEFAULT 0,
  `tenant_id` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_session_jti` (`jti`),
  KEY `idx_session_refresh` (`refresh_token_hash`),
  KEY `idx_session_user` (`user_id`,`status`,`last_active_at`),
  KEY `idx_session_gc` (`refresh_expire_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='登录会话表';
