location / {
    try_files $uri $uri/ /index.php?s=$uri&$args;
}
location /admin {
    try_files $uri $uri/ /admin.php?s=$uri&$args;
}
location /api {
    try_files $uri $uri/ /api.php?s=$uri&$args;
}
location ~ ^/(runtime|application|thinkphp|vendor)/ {
    deny all;
}
