/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('@arco-design/web-vue')['Alert']
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADescriptions: typeof import('@arco-design/web-vue')['Descriptions']
    ADescriptionsItem: typeof import('@arco-design/web-vue')['DescriptionsItem']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    AResult: typeof import('@arco-design/web-vue')['Result']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    ATypographyTitle: typeof import('@arco-design/web-vue')['TypographyTitle']
    IconCheck: typeof import('@arco-design/web-vue/es/icon')['IconCheck']
    IconLanguage: typeof import('@arco-design/web-vue/es/icon')['IconLanguage']
    IconLock: typeof import('@arco-design/web-vue/es/icon')['IconLock']
    IconMenuFold: typeof import('@arco-design/web-vue/es/icon')['IconMenuFold']
    IconMenuUnfold: typeof import('@arco-design/web-vue/es/icon')['IconMenuUnfold']
    IconMoonFill: typeof import('@arco-design/web-vue/es/icon')['IconMoonFill']
    IconPoweroff: typeof import('@arco-design/web-vue/es/icon')['IconPoweroff']
    IconRefresh: typeof import('@arco-design/web-vue/es/icon')['IconRefresh']
    IconSafe: typeof import('@arco-design/web-vue/es/icon')['IconSafe']
    IconStorage: typeof import('@arco-design/web-vue/es/icon')['IconStorage']
    IconSunFill: typeof import('@arco-design/web-vue/es/icon')['IconSunFill']
    IconUser: typeof import('@arco-design/web-vue/es/icon')['IconUser']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./../src/components/ThemeSwitch.vue')['default']
  }
}
